<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Ardalis.SmartEnum" Version="8.2.0" />
		<PackageReference Include="ErrorOr" Version="2.0.1" />
		<PackageReference Include="Google.GenAI" Version="1.17.0" />
		<PackageReference Include="MediatR" Version="12.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="OpenAI" Version="2.13.0" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="Resources\DisasterErrors.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>DisasterErrors.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\DomainErrors.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>DomainErrors.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\NotificationErrors.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>NotificationErrors.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\RefreshTokenErrors.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>RefreshTokenErrors.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\TeamErrors.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>TeamErrors.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\VolunteerErrors.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>VolunteerErrors.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\VolunteerRegisterationErrors.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>VolunteerRegisterationErrors.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="Resources\DisasterErrors.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>DisasterErrors.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\DomainErrors.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>DomainErrors.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\NotificationErrors.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>NotificationErrors.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\RefreshTokenErrors.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>RefreshTokenErrors.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\TeamErrors.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>TeamErrors.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\VolunteerErrors.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>VolunteerErrors.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\VolunteerRegisterationErrors.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>VolunteerRegisterationErrors.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
