//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eghatha.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eghatha.Application.Common.Resources.ApplicationErrors", typeof(ApplicationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already confirmed..
        /// </summary>
        public static string Auth_EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("Auth_EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired access token is not valid..
        /// </summary>
        public static string Auth_ExpiredAccessToken_Invalid {
            get {
                return ResourceManager.GetString("Auth_ExpiredAccessToken_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp code is wrong or expired..
        /// </summary>
        public static string Auth_InvalidOtp {
            get {
                return ResourceManager.GetString("Auth_InvalidOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RefreshToken..
        /// </summary>
        public static string Auth_InvalidRefreshToken {
            get {
                return ResourceManager.GetString("Auth_InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is invalid or has expired..
        /// </summary>
        public static string Auth_RefreshToken_Expired {
            get {
                return ResourceManager.GetString("Auth_RefreshToken_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid userId claim..
        /// </summary>
        public static string Auth_UserIdClaim_Invalid {
            get {
                return ResourceManager.GetString("Auth_UserIdClaim_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disaster not found..
        /// </summary>
        public static string Disaster_NotFound {
            get {
                return ResourceManager.GetString("Disaster_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disaster-resource not found..
        /// </summary>
        public static string DisasterResourceNotFound_NotFound {
            get {
                return ResourceManager.GetString("DisasterResourceNotFound_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification not found..
        /// </summary>
        public static string Notification_NotFound {
            get {
                return ResourceManager.GetString("Notification_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer registeration not found..
        /// </summary>
        public static string RegisterationNotFound_NotFound {
            get {
                return ResourceManager.GetString("RegisterationNotFound_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team has no current disaster.
        /// </summary>
        public static string Team_NoCurrentDisaster {
            get {
                return ResourceManager.GetString("Team_NoCurrentDisaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team is not available.
        /// </summary>
        public static string Team_NotAvailable {
            get {
                return ResourceManager.GetString("Team.NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team not found..
        /// </summary>
        public static string Team_NotFound {
            get {
                return ResourceManager.GetString("Team_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user with this email alreadt exist.
        /// </summary>
        public static string User_UserWithEmailAlreadyExitst {
            get {
                return ResourceManager.GetString("User_UserWithEmailAlreadyExitst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volunteer has no current disaster.
        /// </summary>
        public static string Volunteer_NoCurrentDisaster {
            get {
                return ResourceManager.GetString("Volunteer_NoCurrentDisaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer not found..
        /// </summary>
        public static string Volunteer_NotFound {
            get {
                return ResourceManager.GetString("Volunteer_NotFound", resourceCulture);
            }
        }
    }
}
