//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eghatha.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisasterErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisasterErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eghatha.Domain.Resources.DisasterErrors", typeof(DisasterErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age should be greater than zero..
        /// </summary>
        public static string DisasterErrors_AffectedPerson_Age_Invalid {
            get {
                return ResourceManager.GetString("DisasterErrors_AffectedPerson_Age_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string DisasterErrors_AffectedPerson_Name_Required {
            get {
                return ResourceManager.GetString("DisasterErrors_AffectedPerson_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to affected person no found in this disaster.
        /// </summary>
        public static string DisasterErrors_AffectedPerson_NotFound {
            get {
                return ResourceManager.GetString("DisasterErrors_AffectedPerson_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid status..
        /// </summary>
        public static string DisasterErrors_AffectedPerson_Status_Invalid {
            get {
                return ResourceManager.GetString("DisasterErrors_AffectedPerson_Status_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cannot add affected persons when disaster not in resolved status.
        /// </summary>
        public static string DisasterErrors_CannotAddAffectedPersonsWhenNotResolved {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotAddAffectedPersonsWhenNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report must be generated before archiving the disaster.
        /// </summary>
        public static string DisasterErrors_CannotArchiveWithoutReport {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotArchiveWithoutReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cannot assign a resource when disaster not in a reported or in-progress status.
        /// </summary>
        public static string DisasterErrors_CannotAssignResourceWhenNotInValidStatus {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotAssignResourceWhenNotInValidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cannot assign a team when disaster not in a reported or in-progress status.
        /// </summary>
        public static string DisasterErrors_CannotAssignTeamWhenNotInValidStatus {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotAssignTeamWhenNotInValidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cannot assign a volunteer when disaster not in a reported or in-progress status.
        /// </summary>
        public static string DisasterErrors_CannotAssignVolunteerWhenNotInValidStatus {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotAssignVolunteerWhenNotInValidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all volunteers must be evaluated before closing the disaster.
        /// </summary>
        public static string DisasterErrors_CannotCloseDisasterWithUnevaluatedVolunteers {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotCloseDisasterWithUnevaluatedVolunteers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all resources must be managed before closing the disaster.
        /// </summary>
        public static string DisasterErrors_CannotCloseDisasterWithUnmanagedResources {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotCloseDisasterWithUnmanagedResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report cannot be generated if the disaster is not closed.
        /// </summary>
        public static string DisasterErrors_CannotGenerateReportWhenDisasterNotClosed {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotGenerateReportWhenDisasterNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cannot remove a volunteer when disaster not in repoted status.
        /// </summary>
        public static string DisasterErrors_CannotRemoveVolunteerWhenNotReported {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotRemoveVolunteerWhenNotReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cannot updated affected persons when disaster not in resolved status.
        /// </summary>
        public static string DisasterErrors_CannotUpdateAffectedPersonsWhenDisasterNotResolved {
            get {
                return ResourceManager.GetString("DisasterErrors_CannotUpdateAffectedPersonsWhenDisasterNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city is required.
        /// </summary>
        public static string DisasterErrors_CityRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description type is required.
        /// </summary>
        public static string DisasterErrors_CustomTypeDescriptionRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_CustomTypeDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description is required.
        /// </summary>
        public static string DisasterErrors_DescriptionRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to assign volunteer is already assigned or not available now.
        /// </summary>
        public static string DisasterErrors_FailedToAssign {
            get {
                return ResourceManager.GetString("DisasterErrors_FailedToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to damaged quantity cannot exceed remaining quantity.
        /// </summary>
        public static string DisasterErrors_InvalidDamagedQuantity {
            get {
                return ResourceManager.GetString("DisasterErrors_InvalidDamagedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to participant Scores must be between 1 and 5.
        /// </summary>
        public static string DisasterErrors_InvalidParticipantScore {
            get {
                return ResourceManager.GetString("DisasterErrors_InvalidParticipantScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return quantity cannot exceed remaining quantity.
        /// </summary>
        public static string DisasterErrors_InvalidReturnQuantity {
            get {
                return ResourceManager.GetString("DisasterErrors_InvalidReturnQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid disaster status.
        /// </summary>
        public static string DisasterErrors_InvalidStatus {
            get {
                return ResourceManager.GetString("DisasterErrors_InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location is required.
        /// </summary>
        public static string DisasterErrors_LocationRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to province is required.
        /// </summary>
        public static string DisasterErrors_ProvinceRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_ProvinceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disaster already has a report.
        /// </summary>
        public static string DisasterErrors_ReportAlreadyExist {
            get {
                return ResourceManager.GetString("DisasterErrors_ReportAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reporter contact is required.
        /// </summary>
        public static string DisasterErrors_ReporterContactRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_ReporterContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reporter Id is required.
        /// </summary>
        public static string DisasterErrors_ReporterIdRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_ReporterIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reporter info is required.
        /// </summary>
        public static string DisasterErrors_ReporterInfoRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_ReporterInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reporter name is required.
        /// </summary>
        public static string DisasterErrors_ReporterNameRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_ReporterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource consumption exceeds sent quantity.
        /// </summary>
        public static string DisasterErrors_ResourceConsumptionExceedsSent {
            get {
                return ResourceManager.GetString("DisasterErrors_ResourceConsumptionExceedsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reousnce is not consumable.
        /// </summary>
        public static string DisasterErrors_ResourceIsNotConsumable {
            get {
                return ResourceManager.GetString("DisasterErrors_ResourceIsNotConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource not found.
        /// </summary>
        public static string DisasterErrors_ResourceNotFound {
            get {
                return ResourceManager.GetString("DisasterErrors_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource allocated for a disaster should be greater then zero.
        /// </summary>
        public static string DisasterErrors_ResourceQuantityshouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("DisasterErrors_ResourceQuantityshouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team is not assinged to this disaster.
        /// </summary>
        public static string DisasterErrors_Team_NotFound {
            get {
                return ResourceManager.GetString("DisasterErrors_Team_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team already assigned to disaster.
        /// </summary>
        public static string DisasterErrors_TeamAlreadyAssigned {
            get {
                return ResourceManager.GetString("DisasterErrors_TeamAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team not assigned to this disaster.
        /// </summary>
        public static string DisasterErrors_TeamNotAssignedToDisaster {
            get {
                return ResourceManager.GetString("DisasterErrors_TeamNotAssignedToDisaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title is required.
        /// </summary>
        public static string DisasterErrors_TitleRequired {
            get {
                return ResourceManager.GetString("DisasterErrors_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disaster type is invalid..
        /// </summary>
        public static string DisasterErrors_Type_Invalid {
            get {
                return ResourceManager.GetString("DisasterErrors_Type_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volunteer is not assinged to this disaster.
        /// </summary>
        public static string DisasterErrors_Volunteer_NotFound {
            get {
                return ResourceManager.GetString("DisasterErrors_Volunteer_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volunteer already assigned to disaster.
        /// </summary>
        public static string DisasterErrors_VolunteerAlreadyAssigned {
            get {
                return ResourceManager.GetString("DisasterErrors_VolunteerAlreadyAssigned", resourceCulture);
            }
        }
    }
}
