//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eghatha.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TeamErrorsTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeamErrorsTest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eghatha.Domain.Resources.TeamErrorsTest", typeof(TeamErrorsTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team already has a leader.
        /// </summary>
        public static string TeamErrors_AlreadyHasLeader {
            get {
                return ResourceManager.GetString("TeamErrors.AlreadyHasLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot remove leader.
        /// </summary>
        public static string TeamErrors_CannotRemoveLeader {
            get {
                return ResourceManager.GetString("TeamErrors.CannotRemoveLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot remove member when team in mission.
        /// </summary>
        public static string TeamErrors_CannotRemoveMemberWhenInMission {
            get {
                return ResourceManager.GetString("TeamErrors.CannotRemoveMemberWhenInMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city is required.
        /// </summary>
        public static string TeamErrors_City_Required {
            get {
                return ResourceManager.GetString("TeamErrors.City.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team location must be in syria.
        /// </summary>
        public static string TeamErrors_Location_MustBeInSyria {
            get {
                return ResourceManager.GetString("TeamErrors.Location.MustBeInSyria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location is required.
        /// </summary>
        public static string TeamErrors_Location_Required {
            get {
                return ResourceManager.GetString("TeamErrors.Location.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job-title required.
        /// </summary>
        public static string TeamErrors_Member_JobTitleRequired {
            get {
                return ResourceManager.GetString("TeamErrors.Member.JobTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member cannot set to active in mission.
        /// </summary>
        public static string TeamErrors_Member_Status_CannotSetToActiveWhenInMission {
            get {
                return ResourceManager.GetString("TeamErrors.Member.Status.CannotSetToActiveWhenInMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member status invalid.
        /// </summary>
        public static string TeamErrors_Member_Status_Invalid {
            get {
                return ResourceManager.GetString("TeamErrors.Member.Status.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member status required.
        /// </summary>
        public static string TeamErrors_Member_Status_Required {
            get {
                return ResourceManager.GetString("TeamErrors.Member.Status.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member must be active to become a leader.
        /// </summary>
        public static string TeamErrors_MemberNotActive {
            get {
                return ResourceManager.GetString("TeamErrors.MemberNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team member not found.
        /// </summary>
        public static string TeamErrors_MemberNotFound {
            get {
                return ResourceManager.GetString("TeamErrors.MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team name is required.
        /// </summary>
        public static string TeamErrors_Name_Required {
            get {
                return ResourceManager.GetString("TeamErrors.Name.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to province is required.
        /// </summary>
        public static string TeamErrors_Province_Required {
            get {
                return ResourceManager.GetString("TeamErrors.Province.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource quantity not enough to perform the operation.
        /// </summary>
        public static string TeamErrors_Resource_NotEnough {
            get {
                return ResourceManager.GetString("TeamErrors.Resource.NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the specific resource not found.
        /// </summary>
        public static string TeamErrors_Resource_NotFound {
            get {
                return ResourceManager.GetString("TeamErrors.Resource.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource quantity should be greater than zero.
        /// </summary>
        public static string TeamErrors_Resource_QuantityInvalid {
            get {
                return ResourceManager.GetString("TeamErrors.Resource.QuantityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource status required.
        /// </summary>
        public static string TeamErrors_Resource_StatusRequired {
            get {
                return ResourceManager.GetString("TeamErrors.Resource.StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource type required.
        /// </summary>
        public static string TeamErrors_Resource_TypeRequired {
            get {
                return ResourceManager.GetString("TeamErrors.Resource.TypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speciality invalid.
        /// </summary>
        public static string TeamErrors_Speciality_Invalid {
            get {
                return ResourceManager.GetString("TeamErrors.Speciality.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team speciality is required.
        /// </summary>
        public static string TeamErrors_Speciality_Required {
            get {
                return ResourceManager.GetString("TeamErrors.Speciality.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot set to acitve when in mission.
        /// </summary>
        public static string TeamErrors_Status_CannotSetToActiveWhenInMission {
            get {
                return ResourceManager.GetString("TeamErrors.Status.CannotSetToActiveWhenInMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid team status.
        /// </summary>
        public static string TeamErrors_Status_Invalid {
            get {
                return ResourceManager.GetString("TeamErrors.Status.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team status required.
        /// </summary>
        public static string TeamErrors_Status_Required {
            get {
                return ResourceManager.GetString("TeamErrors.Status.Required", resourceCulture);
            }
        }
    }
}
