//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eghatha.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VolunteerErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VolunteerErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eghatha.Domain.Resources.VolunteerErrors", typeof(VolunteerErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team city is required..
        /// </summary>
        public static string VolunteerErrors_City_Required {
            get {
                return ResourceManager.GetString("VolunteerErrors.City.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipemtn already deleted.
        /// </summary>
        public static string VolunteerErrors_Equipment_AlreadyDeleted {
            get {
                return ResourceManager.GetString("VolunteerErrors.Equipment.AlreadyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolunteerErrors.equipment id is required.
        /// </summary>
        public static string VolunteerErrors_Equipment_IdRequired {
            get {
                return ResourceManager.GetString("VolunteerErrors.Equipment.IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid requpment status.
        /// </summary>
        public static string VolunteerErrors_Equipment_InvalidStatus {
            get {
                return ResourceManager.GetString("VolunteerErrors.Equipment.InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipment name is required.
        /// </summary>
        public static string VolunteerErrors_Equipment_NameRequired {
            get {
                return ResourceManager.GetString("VolunteerErrors.Equipment.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough equipment available to perform the operation..
        /// </summary>
        public static string VolunteerErrors_Equipment_NotEnough {
            get {
                return ResourceManager.GetString("VolunteerErrors.Equipment.NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipment not found.
        /// </summary>
        public static string VolunteerErrors_Equipment_NotFound {
            get {
                return ResourceManager.GetString("VolunteerErrors.Equipment.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipment quantity should be greater than zero.
        /// </summary>
        public static string VolunteerErrors_Equipment_QuantityShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("VolunteerErrors.Equipment.QuantityShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipment category unsupported.
        /// </summary>
        public static string VolunteerErrors_Equipment_UnSupportedCategory {
            get {
                return ResourceManager.GetString("VolunteerErrors.Equipment.UnSupportedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volnteer equipments already has this equipment.
        /// </summary>
        public static string VolunteerErrors_EquipmentAlreadyAssigned {
            get {
                return ResourceManager.GetString("VolunteerErrors.EquipmentAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volunteer equipment is required.
        /// </summary>
        public static string VolunteerErrors_EquipmentRequired {
            get {
                return ResourceManager.GetString("VolunteerErrors.EquipmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years of experience must be greater than zero.
        /// </summary>
        public static string VolunteerErrors_ExperienceMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("VolunteerErrors.ExperienceMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volunteer location is required.
        /// </summary>
        public static string VolunteerErrors_LocationRequired {
            get {
                return ResourceManager.GetString("VolunteerErrors.LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer province is required..
        /// </summary>
        public static string VolunteerErrors_Province_Required {
            get {
                return ResourceManager.GetString("VolunteerErrors.Province.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer score should be greater than zero.
        /// </summary>
        public static string VolunteerErrors_ScoreMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("VolunteerErrors.ScoreMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid volunteer status.
        /// </summary>
        public static string VolunteerErrors_SpecialityInvalid {
            get {
                return ResourceManager.GetString("VolunteerErrors.SpecialityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volunteer status is required.
        /// </summary>
        public static string VolunteerErrors_SpecialityRequired {
            get {
                return ResourceManager.GetString("VolunteerErrors.SpecialityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid volunteer status.
        /// </summary>
        public static string VolunteerErrors_StatusInvalid {
            get {
                return ResourceManager.GetString("VolunteerErrors.StatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volunteer status is required.
        /// </summary>
        public static string VolunteerErrors_StatusRequired {
            get {
                return ResourceManager.GetString("VolunteerErrors.StatusRequired", resourceCulture);
            }
        }
    }
}
