<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="ErrorOr" Version="2.0.1" />
    <PackageReference Include="Google.GenAI" Version="1.17.0" />
		<PackageReference Include="MediatR" Version="12.5.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.4.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
		<PackageReference Include="OpenAI" Version="2.13.0" />
		<PackageReference Include="StackExchange.Redis" Version="2.12.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eghatha.Domain\Eghatha.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Common\Resources\ApplicationErrors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ApplicationErrors.resx</DependentUpon>
    </Compile>
    <Compile Update="Common\Resources\ApplicationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ApplicationMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Common\Resources\ApplicationErrors.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ApplicationErrors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Common\Resources\ApplicationMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ApplicationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
